[package]
name = "ServerSeekerV2-Rescanner"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
toml = "0.8.19"
tokio = { version = "1.0.0", features = ["rt", "rt-multi-thread", "macros"] }
diesel = { version = "2.2.7", features = ["postgres", "numeric"] }
bigdecimal = "0.4.7"
