[package]
name = "ServerSeekerV2-Rescanner"
version = "0.1.0"
edition = "2021"
rust-version = "1.80.0"

[dependencies]
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
toml = "0.8.19"
tokio = { version = "1.0.0", features = ["rt", "rt-multi-thread", "macros"] }
sqlx = { version = "0.8.3", features = ["postgres", "runtime-tokio"] }
indicatif = { version = "0.17.11", features = ["rayon"] }
anyhow = "1.0.97"
futures = "0.3.31"
rayon = "1.10.0"

[target.x86_64-unknown-linux-gnu]
#rustflags = ["-C", "link-arg=--ld-path=/usr/bin/mold", "target-cpu=native"]
#linker = "/usr/bin/clang"
rustflags = ["-C", "link-arg=--ld-path=/usr/bin/mold"]

[profile.release]
strip = true
lto = true
codegen-units = 1
