[package]
name = "ServerSeekerV2-Rescanner"
version = "0.1.0"
edition = "2021"
rust-version = "1.80.0"

[dependencies]
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
toml = "0.8.19"
tokio = { version = "1.0.0", features = ["rt", "rt-multi-thread", "macros"] }
bigdecimal = "0.4.7"
sqlx = { version = "0.8.3", features = ["postgres", "runtime-tokio"] }
