[rescanner]
# Repeat after a scan is complete?
repeat = true
# How long to wait before starting another scan
rescan_delay = 60
# Start of port range
port_range_start = 25565
# End of port range
port_range_end = 25565

[database]
# Database URL
url = "database.yourdomain.xyz"
# Database port
port = 5432
# Database table
table = "postgres"
# Database user
user = "postgres"
# Database user password
password = "SuperSuperSecretPassword"