[scanner]
# Repeat after a scan is complete?
repeat = true
# How long to wait before starting another scan in seconds
scan_delay = 60
# Start of port range
port_range_start = 25565
# End of port range
port_range_end = 25565

[masscan]
# Location of masscans config file
config_file = "masscan.conf"

[database]
# Database URL
host = "database.yourdomain.xyz"
# Database port
port = 5432
# Database table
table = "postgres"
# Database user
user = "postgres"
# Database user password
password = "SuperSuperSecretPassword"

[player_tracking]
# Enable player tracking?
enabled = false
# List of players to track
players = [""]

[country_tracking]
# Enable tracking of country information (requires a valid https://ipinfo.io account token)
enabled = false
# How often to update the country information table in hours (minimum 24 hours)
update_frequency = 48
# IPInfo token
ipinfo_token = ":3"