[rescanner]
repeat = true
rescan_delay = 60
port_range_start = 25565
port_range_end = 25565

[database]
url = "database.yourdomain.xyz"
port = 5432
table = "postgres"
user = "postgres"
password = "SuperSuperSecretPassword"